# Don't change this! Version used to track needed updates.
version = 0

[black_pearl]
chance = 0.1
cooldown = 180

[blade_of_the_grotesque]
selfStunTime = 50
auraStunTime = 50
auraRange = 4.0
selfStunnedArmorBuff = 10
attackerStunnedArmorBuff = 10
cooldown = 500
selfSlow = -0.02
maxAuraWard = 5

[boas_fang]
chance = 0.4
suffocationTime = 100
spitSpeedTime = 80
cooldown = 600
poisonTime = 80
spitDamage = 5.0
spitPushback = 2.0

[earthshatter]
chance = 0.15
cooldown = 600
slamEffectTime = 160

[glimmerstep]
maxStarlight = 10
chance = 0.25
chanceMounted = 0.4
explosionDamagePerStarlight = 3.2
blindTime = 40
baseSpeedFrequency = 200
speedFrequencyPerStack = 10
speedTime = 40
explosionRange = 5
explosionWindup = 60
cooldown = 800
glimmerstepAllyDamage = 0.8
starlightTime = 800

[grandfrost]
chance = 0.25
chillTime = 140
blizzardRange = 5
blizzardStrength = 3.5
blizzardEffectTime = 200
cooldown = 500

[great_slither]
poisonTime = 90
venomTime = 40
chance = 0.25
range = 7
fangDamage = 4.0
fangsVenomTime = 90
fangsSlowTime = 35
cooldown = 300

[lustrous_moxie]
chance = 0.2
cooldown = 400
stunTime = 30
range = 20
aoe = 5
knockbackStrength = 2.0
targetDamage = 15.0
aoeDamage = 10.0

[matterbane]
chance = 0.2
range = 8
damage = 6
cooldown = 1200

[mimicry]
typeCooldown = 400
cooldown = 60
windup = 10

[mimicry.config]

[mimicry.config.longsword]
disabled = false
damage = 6.0
extraDamage = 2.0
knockback = 1.2

[mimicry.config.twinblade]
disabled = false
firstDamage = 5.0
secondDamage = 8.0
effectTime = 80
knockback = 1.5

[mimicry.config.rapier]
disabled = false
damage = 3.0
effectTime = 60

[mimicry.config.sai]
disabled = false
damage = 5.5
effectTime = 80

[mimicry.config.cutlass]
disabled = false
damage = 6.0
pull = 0.8

[mimicry.config.chakram]
disabled = false
duration = 60

[mimicry.config.warglaive]
disabled = false
firstDamage = 5.0
secondDamage = 6.75
effectTime = 80

[mimicry.config.spear]
disabled = false
damage = 8.0
finalDamage = 10.0
effectTime = 80

[mimicry.config.glaive]
disabled = false
damage = 6.0

[mimicry.config.claymore]
disabled = false
damage = 8.0
effectTime = 100
knockback = 1.6

[mimicry.config.scythe]
disabled = false
damage = 10.0
effectTime = 150

[mimicry.config.greataxe]
disabled = false
damage = 8.0
knockback = 2.0

[mimicry.config.greathammer]
disabled = false
damage = 7.5
effectTime = 100

[mimicry.config.dagger]
disabled = false
damage = 6.0
effectTime = 120

[mimicry.config.khopesh]
disabled = false
damage = 8.0
effectTime = 100

[mimicry.config.katana]
disabled = false
damage = 12.0

[mimicry.config.grandsword]
disabled = false
damage = 15.0
effectTime = 120
knockback = 2.5

[mimicry.config.pernach]
disabled = false
damage = 5.5
effectTime = 100

[mimicry.config.lance]
disabled = false
firstDamage = 7.0
secondDamage = 9.0
effectTime = 80
knockback = 1.5

[mimicry.config.great_spear]
disabled = false
slamDamage = 6.0
stabDamage = 10.0
effectTime = 20
knockback = 1.3

[mimicry.config.quarterstaff]
disabled = false
damage = 6.0

[mimicry.config.halberd]
disabled = false
damage = 4.0
effectTime = 180

[mimicry.config.backhand_blade]
disabled = false
damage = 8.0
effectTime = 100

[mimicry.config.deer_horns]
disabled = false
damage = 1.8
effectTime = 80

[mimicry.config.great_katana]
disabled = false
damage = 14.0
extraDamage = 4.0

[molten_flare]
chance = 0.2
radius = 4
radiusEmpowered = 7
activeAttackSpeedBonus = 0.6
cooldown = 300

[ruyi_jingu_bang]
cooldown = 300

[myrmedge]
maxDamageBonus = 0.4
grabTime = 100
cooldown = 300
throwStrength = 1.6

[serpentine_valour]
cooldown = 700
lifespan = 10
damage = 2.0
venomTime = 160
damageBonus = 4.0

[the_pan]
chance = 0.3
knockbackStrength = 20.0

[holylight]
spreadChance = 0.15
blessingHeal = 4.0
cooldown = 800

[darksent]
chance = 0.15
curseDamageMultiplier = 1.5
curseWeakenTime = 100
cooldown = 800

[smouldering_ruin]
cooldown = 800
chance = 0.25
witherTime = 100

[soul_foreseer]
foreseenTime = 160
chance = 0.3
range = 20
effectTime = 80

[stasis]
cooldown = 700
stunTime = 80
chance = 0.2
strikeDamage = 16.0
strikeWindup = 60
range = 4

[the_blood_harvester]
cooldown = 1800
harvestTime = 300
bleedTime = 150
lifesteal = 0.1
harvestLifesteal = 0.2

[the_vessel_breach]
cooldown = 1800
bleedTime = 100
lifesteal = 0.1
rageLifesteal = 0.16
rageTime = 200
startupDamage = 0.3

[tidebreaker]
cooldown = 400
chance = 0.25
cloudTime = 300
range = 15
teleportTime = 200

[timekeeper]
cooldown = 400
nightActiveSlownessTime = 100
dayActiveBlindnessTime = 100
nightPassiveEffectTime = 70
dayPassiveEffectTime = 70
nightDamage = 2.0
dayDamage = 6.0
chance = 0.2

[vipers_call]
vipersCallCooldown = 1200
blacklist = [  ]

[brassturn]
chance = 0.15
stunTime = 15
scrapeTime = 5
sparkChance = 0.25

[cindergorge]
chance = 0.4
thornsDamage = 3.0
fireThornsDamage = 6.0
maxUseTime = 200
range = 5
fireDamage = 5.0
cooldown = 600

[deaths_eyrie]
chance = 0.25
baseBleedTime = 80
additionalBleedTime = 20
cooldown = 550
crowBleedTime = 120
crowBlindTime = 20
crowAttackTimePerCrow = 30
crowDamage = 2.3
deathsEyrieCrowAttackHeal = 0.3

[perforiscus]
bloomTime = 500
cooldown = 800

[revvengine]
p1cooldown = 240
p2cooldown = 360
p3cooldown = 440
p1windup = 10
p2windup = 40
p3windup = 80
chance = 0.2
bleedTime = 80
p1damage = 7
p2damage = 12
p2effectTime = 120
p3damage = 15
p3effectTime = 100
explosionWindup = 80
explosionDamage = 10
damageBuff = 0.6
rangeBuff = 0.5

[exedrill]
cooldown = 250
chance = 0.15
trembleEffectTime = 80
chanceMounted = 0.3
trembleHeatAmount = 6
hitHeatAmount = 1
maxHeat = 25
explosionDamage = 12.0
rockDamage = 6.0
rockSpeed = 0.4
rockStunTime = 14
rocksAmount = 5
earthquakeStrength = 1.8

[culterex]
cooldown = 400
baseDuration = 180
extraDuration = 60
chance = 0.35
durationPerEffectLevel = 60
range = 30