["Mod Config"]
	#Enable gem socket injection into items via loot modifier
	enableSocketGemInjector = true
	#Chance to insert a random gem into each socket slot, 1.0 means 100%
	# Default: 0.3
	# Range: 0.0 ~ 1.0
	socketGemChance = 0.3
	#If false, Adaptive Spell Power Affixes can apply to any compatible item regardless of spell school.
	#If true, affixes will only apply to items that already grant spell power of the matching school.
	strictSpellSchoolMatching = true
	#Map of item Resource Locations to School Type IDs for Adaptive Spell Power Affixes
	#Example: modid:itemid|modid:schoolid
	#You can also set multiple schools: modid:itemid|modid:schoolid|modid:schoolid
	irons_items = []
