[element_attachment]
	#没有显式覆盖的法术的默认元素附着量
	# Default: 200
	# Range: > 0
	default = 200
	#ICD 攻击步长：允许在第 1、1+步长、1+2*步长... 次攻击时应用元素
	#设置为 3 表示允许第 1、4、7 次攻击等
	# Default: 3
	# Range: > 1
	icd_hit_step = 3
	#ICD 时间窗口（游戏刻）：如果上次应用时间超过此窗口则允许应用
	#50 刻 = 2.5 秒（20 TPS）
	# Default: 50
	# Range: > 0
	icd_time_ticks = 50
	#单个法术覆盖，格式：modid:spell_id=数量
	#多个条目用逗号分隔
	#示例：irons_spellbooks:firebolt=250, irons_spellbooks:ice_shard=150
	#未知或格式错误的条目将被忽略
	overrides = ""
	#单个法术元素附着覆盖，格式：modid:spell_id=元素ID
	#允许特定法术附着自定义元素而不是使用基于学派的映射
	#多个条目用逗号分隔
	#示例：irons_spellbooks:firebolt=lightning, irons_spellbooks:ice_shard=fire
	#元素ID应与 element_attachments 数据文件中定义的匹配
	#未知或格式错误的条目将被忽略
	spell_element_overrides = ""

[weapon]
	#武器可附着的最大元素量
	# Default: 20000
	# Range: > 1
	max_element_amount = 20000
